# Generated by Django 5.2.6 on 2025-09-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp_accounts', '0002_account_created_at_alter_account_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
