# Generated by Django 5.2.6 on 2025-09-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp_products', '0002_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
    ]
