# Generated by Django 5.2.6 on 2025-09-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp_products', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
