# Generated by Django 5.2.6 on 2025-09-11 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nexusapp_accounts', '0001_initial'),
        ('nexusapp_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexusapp_accounts.account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexusapp_products.product')),
            ],
        ),
    ]
